In [1]:
import pandas as pd

df = pd.read_csv("iris.csv")

df.head()


sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [2]:
import numpy as np
np.unique(df['variety'])


array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [3]:
df['class'] = df['variety'].replace({"Setosa": 0, "Versicolor": 1, "Virginica": 2})

/tmp/ipykernel_4391/3806576535.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['class'] = df['variety'].replace({"Setosa": 0, "Versicolor": 1, "Virginica": 2})


In [4]:
df = df.dropna()

In [5]:
df = df.fillna(0)

In [6]:
df = df.drop_duplicates()

In [7]:
df.describe()

sepal.length  sepal.width  petal.length  petal.width       class
count    149.000000   149.000000    149.000000   149.000000  149.000000
mean       5.843624     3.059732      3.748993     1.194631    0.993289
std        0.830851     0.436342      1.767791     0.762622    0.817847
min        4.300000     2.000000      1.000000     0.100000    0.000000
25%        5.100000     2.800000      1.600000     0.300000    0.000000
50%        5.800000     3.000000      4.300000     1.300000    1.000000
75%        6.400000     3.300000      5.100000     1.800000    2.000000
max        7.900000     4.400000      6.900000     2.500000    2.000000

In [8]:
df.info() 
#variety este object deoarece in pandas(fiind bazat pe C) nu exista data type string, 
# este un array de char-uri

<class 'pandas.core.frame.DataFrame'>
Index: 149 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  149 non-null    float64
 1   sepal.width   149 non-null    float64
 2   petal.length  149 non-null    float64
 3   petal.width   149 non-null    float64
 4   variety       149 non-null    object 
 5   class         149 non-null    int64  
dtypes: float64(4), int64(1), object(1)
memory usage: 8.1+ KB


In [9]:
# lista_valori = df.stack().tolist()
# print(lista_valori)

df['x'] = df[df.columns[:4]].values.tolist()
df['x']

0      [5.1, 3.5, 1.4, 0.2]
1      [4.9, 3.0, 1.4, 0.2]
2      [4.7, 3.2, 1.3, 0.2]
3      [4.6, 3.1, 1.5, 0.2]
4      [5.0, 3.6, 1.4, 0.2]
               ...         
145    [6.7, 3.0, 5.2, 2.3]
146    [6.3, 2.5, 5.0, 1.9]
147    [6.5, 3.0, 5.2, 2.0]
148    [6.2, 3.4, 5.4, 2.3]
149    [5.9, 3.0, 5.1, 1.8]
Name: x, Length: 149, dtype: object

In [10]:
df['y'] = df['class'].apply(lambda x: x+1)
df ['y']

0      1
1      1
2      1
3      1
4      1
      ..
145    3
146    3
147    3
148    3
149    3
Name: y, Length: 149, dtype: int64

In [11]:
df.describe()

sepal.length  sepal.width  petal.length  petal.width       class  \
count    149.000000   149.000000    149.000000   149.000000  149.000000   
mean       5.843624     3.059732      3.748993     1.194631    0.993289   
std        0.830851     0.436342      1.767791     0.762622    0.817847   
min        4.300000     2.000000      1.000000     0.100000    0.000000   
25%        5.100000     2.800000      1.600000     0.300000    0.000000   
50%        5.800000     3.000000      4.300000     1.300000    1.000000   
75%        6.400000     3.300000      5.100000     1.800000    2.000000   
max        7.900000     4.400000      6.900000     2.500000    2.000000   

                y  
count  149.000000  
mean     1.993289  
std      0.817847  
min      1.000000  
25%      1.000000  
50%      2.000000  
75%      3.000000  
max      3.000000

In [12]:
df.to_csv("iris_ok.csv", index=False)

In [13]:
#from sklearn.datasets import load_iris
#from sklearn.model_selection import train_test_split
#from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

neigh = KNeighborsClassifier(n_neighbors=len(np.unique(df['y'])))

In [14]:
neigh.fit(df[df.columns[:4]].values.tolist(), df['y'])

KNeighborsClassifier(n_neighbors=3)

In [15]:
neigh.predict([[5.2,3.6,1.39,0.2]])

array([1])

In [16]:
from pyod.models.knn import KNN
from sklearn.model_selection import train_test_split

In [17]:
clf = KNN()
clf.fit(df[df.columns[:4]].values.tolist(), df['y'])

/usr/local/lib/python3.10/dist-packages/pyod/models/base.py:430: UserWarning: y should not be presented in unsupervised learning.
  warnings.warn(


KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [18]:
y_train_pred = clf.labels_ # Binary labels (0: inliners, 1: outliers)
clf.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
y_train_scores = clf.decision_scores_ # raw outlier scores
clf.decision_scores_ # raw outlier scores

array([0.14142136, 0.2236068 , 0.26457513, 0.26457513, 0.2236068 ,
       0.38729833, 0.31622777, 0.2236068 , 0.36055513, 0.2       ,
       0.33166248, 0.3       , 0.24494897, 0.5       , 0.58309519,
       0.64031242, 0.4       , 0.17320508, 0.51961524, 0.31622777,
       0.36055513, 0.28284271, 0.53851648, 0.38729833, 0.4472136 ,
       0.3       , 0.26457513, 0.2236068 , 0.2236068 , 0.24494897,
       0.2236068 , 0.34641016, 0.45825757, 0.47958315, 0.2       ,
       0.33166248, 0.36055513, 0.3       , 0.3       , 0.17320508,
       0.24494897, 0.79372539, 0.31622777, 0.42426407, 0.47958315,
       0.26457513, 0.33166248, 0.2236068 , 0.28284271, 0.2236068 ,
       0.51961524, 0.38729833, 0.50990195, 0.43588989, 0.38729833,
       0.37416574, 0.45825757, 0.78740079, 0.31622777, 0.53851648,
       0.72111026, 0.37416574, 0.58309519, 0.43588989, 0.53851648,
       0.38729833, 0.42426407, 0.37416574, 0.70710678, 0.3       ,
       0.46904158, 0.41231056, 0.43588989, 0.45825757, 0.38729